### ISSUE TITLE
warning:erroneous pipeline: no element "gst_tf_detection"

### ISSUE THREAD

**Issue by saisarat12345** [jackersson/gst-plugins-tf#4]
hi taras,i was trying to implement this tutorial ,but i couldn’t able to register the gst_tf_detection plugin.here is the path that i was trying to export as specified above in this tutorial:

export GST_PLUGIN_PATH=$GST_PLUGIN_PATH:/home/sai/venv/lib/gstreamer-1.0/:/home/sai/gst-plugins-tf/gst/python/gst_tf_detection.py

i can see that libgstpython.cpython-36m-x86_64-linux-gnu.so file is present in the directory.but still when i was trying to run the pipe line i was getting error as “erroneous pipeline: no element “gst_tf_detection” “.
kindly please help to sort this out..thanks in advance!

**Comment by jackersson** [comment]
Hi, 

As mentioned in Readme, - try to use the next export:
```
export GST_PLUGIN_PATH=$GST_PLUGIN_PATH:$PWD/venv/lib/gstreamer-1.0/:$PWD/gst/
```
where:
- $GST_PLUGIN_PATH - previous plugins path
- $PWD/venv/lib/gstreamer-1.0 - path to **libgstpython.cpython-36m-x86_64-linux-gnu.so**
- $PWD/gst/ - path to **python/** folder with *.py plugins implementations (in your case: /home/sai/gst-plugins-tf/gst/)

Also sometimes cleaning gstreamer cache helps: 
```
rm -rf ~/.cache/gstreamer-1.0/
```

**Comment by saisarat12345** [comment]
Thanks for the reply taras, and as you said i was doing as  in the screenshot attached below
![Capture](https://user-images.githubusercontent.com/40355527/91918347-4274c600-ece0-11ea-8662-c6dae7193037.PNG)

still i am getting no plugin error..am i doing anything wrong in exporting?you said that the $GST_PLUGIN_PATH is the previous plugins path and i took this path from gst-inspect-1.0 .is that correct way of taking old plugin path?

**Comment by jackersson** [comment]
In your case GST_PLUGIN_PATH should be like this: 
`/usr/lib/x86_64-linux-gnu/gstreamer-1.0:/home/sau/gst-plugins-tf/myenv/lib/gstreamer-1.0:/home/sai/gst-plugins-tf/gst/`

Get rid of libgstpython.cpython-36m-x86_64-linux-gnu.so, and python/

**Comment by saisarat12345** [comment]
Thanks a lot Taras !! it worked for me.so i was missing in export path declaration..what a foolish am i..Anyways thanks for the quick response and also for the GREAT TUTORIAL!
